authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Entities from Emoji data tables"
keywords = ["Entities", "Emoji"]
license = "MIT"
name = "Emoji_Entities"
uuid = "fd8f23de-bd2f-5c75-921c-0c9ab51355f5"
version = "1.0.3"

[deps]
StrTables = "9700d1a9-a7c8-5760-9816-a99fda30bb8f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
StrTables = "1"
