name = "Emoji_Entities"
desc = "Entities from Emoji data tables"
keywords = ["Entities", "Emoji"]
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
license = "MIT"
repo = "https://github.com/JuliaString/Emoji_Entities.jl.git"
git-tree-sha1 = "30baf46453092c81f312ca4013018f7691f524aa"
uuid = "fd8f23de-bd2f-5c75-921c-0c9ab51355f5"

version = "0.2.2"
[deps]
StrTables = "9700d1a9-a7c8-5760-9816-a99fda30bb8f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pkg = "fe1c5a76-5840-53d2-82f9-288dd83ce2ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
