authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Entities from Emoji data tables"
keywords = ["Entities", "Emoji"]
license = "MIT"
name = "Emoji_Entities"
uuid = "fd8f23de-bd2f-5c75-921c-0c9ab51355f5"
version = "1.0.0"

[deps]
StrTables = "9700d1a9-a7c8-5760-9816-a99fda30bb8f"

JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6" # Only needed for build!

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.0.0"
StrTables = "≥ 1.0.0"
