authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Build entities from Emoji data tables"
keywords = ["Entities", "Emoji"]
license = "MIT"
name = "Emoji_Entities Build"
version = "1.0.2"

[deps]
StrTables = "9700d1a9-a7c8-5760-9816-a99fda30bb8f"

JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6" # Only needed for build!

[compat]
julia = "1"
StrTables = "1"
JSON = "0.21"
